name: CI

on: [push, pull_request]

defaults:
  run:
    shell: pwsh

env:
  dotnet-version: "3.1.x"
  node-version: "12.x"

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.dotnet-version }}
    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.node-version }}
    - name: Install dev deps
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.AZ_TOKEN }}
      run: pwsh -c ./tools.ps1 dev-deps
    - name: Restore
      run: pwsh -c ./tools.ps1 restore
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: pwsh -c ./tools.ps1 test
    - name: Benchmark
      run: pwsh -c ./tools.ps1 benchmark
    - name: Generate reports
      run: pwsh -c ./tools.ps1 report
    - name: Upload reports
      uses: actions/upload-artifact@master
      with:
        name: ci-${{ matrix.os }}
        path: ./reports
  invoke-cd:
    needs: ci
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PA_TOKEN }}
        event-type: cd
